"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class block_goal_t(object):

    __slots__ = ["timestamp", "transform"]

    __typenames__ = ["int64_t", "double"]

    __dimensions__ = [None, [4, 4]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.transform = [ [ 0.0 for dim1 in range(4) ] for dim0 in range(4) ]
        """ LCM Type: double[4][4] """

    def encode(self):
        buf = BytesIO()
        buf.write(block_goal_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        for i0 in range(4):
            buf.write(struct.pack('>4d', *self.transform[i0][:4]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != block_goal_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return block_goal_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = block_goal_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.transform = []
        for i0 in range(4):
            self.transform.append(struct.unpack('>4d', buf.read(32)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if block_goal_t in parents: return 0
        tmphash = (0x4deb08ea0d2146fb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if block_goal_t._packed_fingerprint is None:
            block_goal_t._packed_fingerprint = struct.pack(">Q", block_goal_t._get_hash_recursive([]))
        return block_goal_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", block_goal_t._get_packed_fingerprint())[0]

